name: Databricks CI/CD

on:
  push:
    branches:
      - "*"
      - "**"

env:
    DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
    DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    REPO_DIRECTORY: /Repos/${{ github.ref_name  }}/${{ github.event.repository.name }}
    TESTS_DIRECTORY: tests
    REQUIREMENTS_PATH: tests/requirements.txt
    CLUSTER_CONFIG_PATH: tests/cluster.json

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Update Databricks Repo
            uses: ./.github/actions/repos
            with:
              databricks_host: ${{ env.DATABRICKS_HOST }}
              databricks_token: ${{ env.DATABRICKS_TOKEN }}
              repo_url:  ${{ github.event.repository.url }}
              branch: ${{ github.ref_name  }}
              databricks_path: ${{ env.REPO_DIRECTORY }}

          - name: Run Tests
            uses: ./.github/actions/jobs
            with:
              databricks_host: ${{ env.DATABRICKS_HOST }}
              databricks_token: ${{ env.DATABRICKS_TOKEN }}
              repo_url:  ${{ github.event.repository.url }}
              branch: ${{ github.ref_name  }}
              folder_path: ${{ env.TESTS_DIRECTORY}}
              requirements_path: ${{ env.REQUIREMENTS_PATH }}
              cluster_config_path: ${{ env.CLUSTER_CONFIG_PATH }}
