name: Terraform

on:
  workflow_dispatch

env:
  TERRAFORM_VERSION: 1.6.4
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  GIT_PROVIDER: "gitHub"


jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Run terraform init
      run: |
        terraform init
        terraform plan -var="databricks_host=${{ env.DATABRICKS_HOST }}" -var="databricks_token=${{ env.DATABRICKS_TOKEN }}" -var="git_username=${{ github.repository_owner }}" -var="git_provider=${{ env.GIT_PROVIDER }} -var="git_token=${{ env.GIT_TOKEN }}"
