name: Echo

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Echo
      run: echo ${{ github.ref_type }}
  